### ISSUE TITLE
`ketchup status`: multiple jobids and format

### ISSUE THREAD

**Issue by lorisercole** [dgbowl/tomato#32]
- When multiple jobs have been submitted, AiiDA may ask for the status of multiple jobs at the same time.
It would be nice if `ketchup status` could accept multiple jobids as argument: e.g.
```
ketchup status 1 2 3
```
which is equivalent to
```
ketchup status 1 && ketchup status 2 && ketchup status 3
```
- Furthermore, maybe the output of this command could be rendered in a nicer format (also easier to parse), such as yaml-style:
```
- jobid: 1
  name: job-1
  status: q
  submitted: '2022-06-28 16:09:31.463749+00:00'
- jobid: 2
  name: job-2
  status: q
  submitted: '2022-06-28 16:09:31.463749+00:00'
- jobid: 3
  name: job-3
  status: q
  submitted: '2022-06-28 16:09:31.463749+00:00'
```
- Feel free to add any other scheduler information that could be useful to retrieve for debug purposes (e.g. pipeline used, ...).

- Finally another useful feature would be to be able to see the list of all jobs (including completed ones). E.g. with a command like:
```
ketchup status queue -a
```

**Comment by PeterKraus** [comment]
@lorisercole, not a problem. I can re-do all the outputs to `yaml`-like format, if you want?

**Comment by lorisercole** [comment]
Sounds good! Not urgent, but nice to have at a certain point.
