### ISSUE TITLE
Submitting queued jobs may not be robust

### ISSUE THREAD

**Issue by g-kimbell** [dgbowl/tomato#88]
- At least in 0.2.x, I cannot easily tell if this applies to 1.0

- We queue several jobs for one sample on one pipeline

- The Daemon iterates through sorted jobs, checking pipeline statuses in each iteration

- If the pipeline changes status while iterating through jobs, the wrong job can be submitted

**Comment by PeterKraus** [comment]
Yes, this was a suspicion in `0.2.x`. I am not sure where exactly the race condition was, though.

In `1.0`, we avoid this by pulling the information about the daemon status only once per iteration, and then acting on this copy for the rest of the rest of the loop:
https://github.com/dgbowl/tomato/blob/0a6c4d70185f193d92fb9dbe165b1c6cebbfb223/src/tomato/daemon/job.py#L245-L249

**Comment by PeterKraus** [comment]
We should probably stress-test this in 1.0 just in case. `main` branch should be ready now with 2 drivers available for testing.

**Comment by g-kimbell** [comment]
Just to confirm - this happened to me 4 times out of ~20 when submitting 2 jobs to each pipeline with 0.2.x, but pulling the information once at the beginning should surely fix that.

However I could imagine trying to submit 2 jobs to 1 pipeline, if the first fails for some reason you would not want the second to be submitted instead.

**Comment by PeterKraus** [comment]
This should be covered by the `counter_stresstest` implemented in #110.
